theme = "modern"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB ({Mup}%)"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}° max, {average}° avg"
chip = "*-isa-*"

[[block]]
block = "load"
interval = 1
format = "{1m}"


[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = false
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} km/s"
service = { name = "openweathermap", api_key = "d2babfddec55c71419de401e98172c02", city_id = "756135", units = "metric" }

[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %I:%M"

[[block]]
block = "battery"
