theme = "modern"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}"
format_swap = "{swap_used}/{swap_total}"
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max} max, {average} avg"
chip = "*-isa-*"

[[block]]
block = "load"
interval = 1
format = "{1m}"


[[block]]
block = "net"
device = "wlp3s0"
format = "{ssid} {signal_strength} {ip} {speed_down;K*b}"
interval = 5

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}"
service = { name = "openweathermap", api_key = "d2babfddec55c71419de401e98172c02", city_id = "756135", units = "metric" }

[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %I:%M"

[[block]]
block = "battery"
